### ISSUE TITLE
NordVPN

### ISSUE THREAD

**Issue by fluboy** [saveriomiroddi/rpi_vpn_router#34]
Hello, 
im currently looking to Setup my Raspberry Pi as an VPN Router. I don't have too much experience with the Pi as I only used it as a Kodi Mediacenter. I'd like to know if with this project it would be possible to use NordVPN and if swapping between servers e.g. US to UK would be possible via Phone Commands.

best regards
Patrick

**Comment by saveriomiroddi** [comment]
Hello! So:

1. integrating alternative VPN providers is fairly straightforward (although not trivial); the project is well organized, so it would be a matter of placing the configuration files in a directory (see [PIA example](https://github.com/saveriomiroddi/rpi_vpn_router/tree/master/configfiles/etc/openvpn/pia)), then give the choice to the user (right now, the files are [modified in place](https://github.com/saveriomiroddi/rpi_vpn_router/blob/master/install_vpn_router.sh#L344), and copied from the project fixed location).
I could do this, but it would require somebody to give me a NordVPN account access.
2. swapping between servers on the fly is not possible, and not planned to implement, since it would be a new feature; this project aims at setting up the given VPN connection permanently.
